# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\lyh\eric work\test.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import chart
from chart import MyAccelDynamicMplCanvas, My3DDynamicMplCanvas, MyGyroDynamicMplCanvas

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(1352, 686)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 1331, 671))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.LEIP = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LEIP.sizePolicy().hasHeightForWidth())
        self.LEIP.setSizePolicy(sizePolicy)
        self.LEIP.setMaximumSize(QtCore.QSize(80, 16777215))
        self.LEIP.setAlignment(QtCore.Qt.AlignCenter)
        self.LEIP.setObjectName("LEIP")
        self.horizontalLayout.addWidget(self.LEIP)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.LEPort = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.LEPort.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LEPort.sizePolicy().hasHeightForWidth())
        self.LEPort.setSizePolicy(sizePolicy)
        self.LEPort.setMaximumSize(QtCore.QSize(50, 16777215))
        self.LEPort.setAlignment(QtCore.Qt.AlignCenter)
        self.LEPort.setObjectName("LEPort")
        self.horizontalLayout.addWidget(self.LEPort)
        self.BtnCon = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.BtnCon.setMaximumSize(QtCore.QSize(60, 16777215))
        self.BtnCon.setObjectName("BtnCon")
        self.horizontalLayout.addWidget(self.BtnCon)
        self.BtnDiscon = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.BtnDiscon.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnDiscon.sizePolicy().hasHeightForWidth())
        self.BtnDiscon.setSizePolicy(sizePolicy)
        self.BtnDiscon.setMaximumSize(QtCore.QSize(70, 16777215))
        self.BtnDiscon.setObjectName("BtnDiscon")
        self.horizontalLayout.addWidget(self.BtnDiscon)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 2)
        self.horizontalLayout.setStretch(4, 2)
        self.horizontalLayout.setStretch(5, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(5, -1, 0, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        # self.CBA = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        # self.CBA.setChecked(True)
        # self.CBA.setObjectName("CBA")
        # self.horizontalLayout_7.addWidget(self.CBA)
        # self.CBG = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        # self.CBG.setObjectName("CBG")
        # self.horizontalLayout_7.addWidget(self.CBG)
        # self.CBE = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        # self.CBE.setObjectName("CBE")
        # self.horizontalLayout_7.addWidget(self.CBE)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(2, -1, 3, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.RBRealTime = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.RBRealTime.setEnabled(False)
        self.RBRealTime.setChecked(True)
        self.RBRealTime.setObjectName("RBRealTime")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.RBRealTime)
        self.horizontalLayout_6.addWidget(self.RBRealTime)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_6.addItem(spacerItem)
        self.RBHistory = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.RBHistory.setEnabled(False)
        self.RBHistory.setObjectName("RBHistory")
        self.buttonGroup.addButton(self.RBHistory)
        self.horizontalLayout_6.addWidget(self.RBHistory)
        self.BtnRef = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.BtnRef.setEnabled(False)
        self.BtnRef.setCheckable(False)
        self.BtnRef.setObjectName("BtnRef")
        self.horizontalLayout_6.addWidget(self.BtnRef)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.BtnShow = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.BtnShow.setObjectName("BtnShow")
        self.horizontalLayout_6.addWidget(self.BtnShow)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(2, 1)
        self.horizontalLayout_6.setStretch(3, 1)
        self.horizontalLayout_6.setStretch(5, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, 3, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, -1, 3, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.treeView = QtWidgets.QTreeView(self.verticalLayoutWidget_2)
        self.treeView.setObjectName("treeView")
        self.horizontalLayout_5.addWidget(self.treeView)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.eulerWidget = My3DDynamicMplCanvas(self.verticalLayoutWidget_2)
        self.eulerWidget.setObjectName("eulerWidget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.eulerWidget)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_2.addWidget(self.eulerWidget)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(4, 10)
        self.verticalLayout_2.setStretch(5, 20)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.accelWidget = MyAccelDynamicMplCanvas(self.verticalLayoutWidget_2)
        self.accelWidget.setObjectName("accelWidget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.accelWidget)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_3.addWidget(self.accelWidget)
        self.gyroWidget = MyGyroDynamicMplCanvas(self.verticalLayoutWidget_2)
        self.gyroWidget.setObjectName("gyroWidget")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.gyroWidget)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_3.addWidget(self.gyroWidget)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 10)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.horizontalSlider = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.horizontalSlider.setEnabled(False)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_3.addWidget(self.horizontalSlider)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout.setStretch(0, 30)
        self.verticalLayout.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Monitor"))
        self.label.setText(_translate("MainWindow", "IP:"))
        self.LEIP.setText(_translate("MainWindow", "192.168.1.14"))
        self.label_2.setText(_translate("MainWindow", "Port:"))
        self.LEPort.setText(_translate("MainWindow", "12345"))
        self.BtnCon.setText(_translate("MainWindow", "Connect"))
        self.BtnDiscon.setText(_translate("MainWindow", "Disconnect"))
        # self.CBA.setText(_translate("MainWindow", "ACCEL"))
        # self.CBG.setText(_translate("MainWindow", "GYRO"))
        # self.CBE.setText(_translate("MainWindow", "Euler angle "))
        self.RBRealTime.setText(_translate("MainWindow", "RealTime"))
        self.RBHistory.setText(_translate("MainWindow", "History"))
        self.BtnRef.setText(_translate("MainWindow", "Reflesh"))
        self.BtnShow.setText(_translate("MainWindow", "Show"))
        self.label_3.setText(_translate("MainWindow", "file:"))
        self.label_4.setText(_translate("MainWindow", "progress："))